### ISSUE TITLE
运行失败，错误6007

### ISSUE THREAD

**Issue by ElderDoge** [wherelse/cloudflare-ddns-script#1]
树莓派运行 bash /home/pi/cloudflare-ddns.sh 出错：

API UPDATE FAILED. DUMPING RESULTS:
{"success":false,"errors":[{"code":6007,"message":"Malformed JSON in request body"}],"messages":[],"result":null}

**Comment by ElderDoge** [comment]
经测试，当ip_index="internet"时，可以正常运行

**Comment by wherelse** [comment]
> 经测试，当ip_index="internet"时，可以正常运行
在ip_index="local"时不能运行是吗，能提供一下ifconfig的截图吗

**Comment by ElderDoge** [comment]
是的
![image](https://user-images.githubusercontent.com/33365476/77916495-bc38fb80-72cb-11ea-96f1-a44798bbb13e.png)

**Comment by wherelse** [comment]
> 是的

应该是网络问题，我这里用本地方式获取可以更新，没有问题，你可以改成local获取后尝试删除`/home/pi`目录下的`ip.txt`,`cloudflare.ids`后再次尝试运行脚本

**Comment by ElderDoge** [comment]
已经尝试了你说的方法，结果还是一样的错误
