### ISSUE TITLE
能解析不同二级域名到同一个动态地址吗?

### ISSUE THREAD

**Issue by 549751001** [wherelse/cloudflare-ddns-script#12]
如题,网络环境是家宽,想解析两个(或多个)二级域名到同一个家宽网络底下对应不同端口,然后用nginx反代,想问问如何实现.

**Comment by wherelse** [comment]
将不同的二级域名解析到一个地址就可以了，不同端口反代处理就行

**Comment by 549751001** [comment]
就是不知道如何添加一个二级域名,这样写吗？
record_name="a.google.com,b.google.com"

**Comment by 549751001** [comment]
好的,谢了
