### ISSUE TITLE
通过cloudflare解析eu.org失败

### ISSUE THREAD

**Issue by gh74521** [wherelse/cloudflare-ddns-script#14]
按照教程来, 确定没有其它错误,但是还是失败, 且均已执行 rm cloudflare.ids,

更换了zone_name和 record_name , 错误提示分别为:
①

> zone_name="12345.eu.org"   #你的域名,your root domain address
> record_name="wwww.12345.eu.org" #完整域名,your full domain address

record_type="AAAA"
**提示错误:**
API UPDATE FAILED. DUMPING RESULTS:
{
  "code": 1001,
  "error": "method_not_allowed"
}

②

> zone_name="eu.org"   #你的域名,your root domain address
> record_name="wwww.12345.eu.org" #完整域名,your full domain address

record_type="AAAA"
**提示错误:**
API UPDATE FAILED. DUMPING RESULTS:

③
zone_name="eu.org"   #你的域名,your root domain address
record_name="12345.eu.org" #完整域名,your full domain address
record_type="AAAA"
**提示错误:**
API UPDATE FAILED. DUMPING RESULTS:
{"result":null,"success":false,"errors":[{"code":7003,"message":"Could not route to /client/v4/zones/dns_records/, perhaps your object identifier is invalid?"}],"messages":[]}

**Comment by laaArmy** [comment]
一样
