### ISSUE TITLE
在openwrt上运行失败

### ISSUE THREAD

**Issue by msher100** [wherelse/cloudflare-ddns-script#2]
在一台openwrt路由上运行失败。路由已经获取ipv6，并且手动在cloudflare上登录了一条AAAA记录，域名可以正常访问。运行bash ..../cloudflare-ddns.sh后的提示为：

> API UPDATE FAILED. DUMPING RESULTS:
{"success":false,"errors":[{"code":7003,"message":"Could not route to \/zones\/dns_records, perhaps your object identifier is invalid?"},{"code":7000,"message":"No route for that URI"}],"messages":[],"result":null}

截图如下：
![image](https://user-images.githubusercontent.com/55918381/78939539-ea49e700-7ae6-11ea-9564-8a98cb24b348.png)

**Comment by wherelse** [comment]
我没在op上验证过是否可用，不过填写的内容可能有问题

**Comment by carbule-bar** [comment]
删除sh其外的文件，因为脚本会获取那些文件里面的值，但是如果第一次失败了，那些文件里值是错误的
