### ISSUE TITLE
API UPDATE FAILED

### ISSUE THREAD

**Issue by blankxiv** [wherelse/cloudflare-ddns-script#7]
"code": 1001,
  "error": "method_not_allowed"

**Comment by xx-sep** [comment]
> "code": 1001, "error": "method_not_allowed"

在cf没有添加这条解析就会出现该问题, 不过理论上在没有的情况下 使用create dns record就完美了

**Comment by blankxiv** [comment]
> > "code": 1001, "error": "method_not_allowed"
> 
> 
> 
> 在cf没有添加这条解析就会出现该问题, 不过理论上在没有的情况下 使用create dns record就完美了

并不是这个原因导致的
